/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTree: typeof import('element-plus/es')['ElTree']
    MapBtn: typeof import('./src/components/MapBtn/index.vue')['default']
    MapChart: typeof import('./src/components/MapChart/index.vue')['default']
    MapDialog: typeof import('./src/components/MapDialog/index.vue')['default']
    MapTable: typeof import('./src/components/MapTable/index.vue')['default']
    MapTabs: typeof import('./src/components/MapTabs/index.vue')['default']
    RankColumn: typeof import('./src/components/RankColumn/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
